### ISSUE TITLE
No rings in the visualization of the Saturn system

### ISSUE THREAD

**Issue by Postrediori** [typpo/spacekit#22]
There are no rings displayed when the Saturn example is run on the following configuration:
- Firefox 69 and 70
- Windows 10 x64
- i5-5200U
- integrated GPU

![зображення](https://user-images.githubusercontent.com/856993/67310632-d0035900-f506-11e9-9843-b389fba28842.png)

Firefox JS console shows the following errors:

```
spacekit.js:18227:13

THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog C:\fakepath(100,90-116): internal error: invalid access of unbound variable

Warning: D3D shader compilation failed with default flags. (ps_5_0)
 Retrying with skip validation
C:\fakepath(100,90-116): internal error: invalid access of unbound variable

Warning: D3D shader compilation failed with skip validation flags. (ps_5_0)
 Retrying with skip optimization
C:\fakepath(100,90-116): internal error: invalid access of unbound variable

Warning: D3D shader compilation failed with skip optimization flags. (ps_5_0)

Failed to create D3D Shaders  spacekit.js:18227:13
    WebGLProgram https://typpo.github.io/spacekit/build/spacekit.js:18227
    acquireProgram https://typpo.github.io/spacekit/build/spacekit.js:18606
    initMaterial https://typpo.github.io/spacekit/build/spacekit.js:24575
    setProgram https://typpo.github.io/spacekit/build/spacekit.js:24716
    renderBufferDirect https://typpo.github.io/spacekit/build/spacekit.js:23775
    renderObject https://typpo.github.io/spacekit/build/spacekit.js:24492
    renderObjects https://typpo.github.io/spacekit/build/spacekit.js:24462
    render https://typpo.github.io/spacekit/build/spacekit.js:24264
    animate https://typpo.github.io/spacekit/build/spacekit.js:58819
```

I'm going to check some Chromium-based browser to check whether the problem is Firefox-specific or it's something missing in Intel's GPU drivers.

**Comment by typpo** [comment]
Thanks for the report.  I'm on Mac Firefox and am able to see the rings.  So I suspect it may be some combination of OS+GPU.

[Here is an old but potentially related issue](https://github.com/mrdoob/three.js/issues/8161).  However, my [ring shader](https://github.com/typpo/spacekit/blob/master/src/shaders.js#L262) doesn't return any structs.  So I'm not sure the fix is directly applicable.

**Comment by Postrediori** [comment]
> So I suspect it may be some combination of OS+GPU.
Yes, this happens to be a Windows-specific issue. Ubuntu 18.04 on the same machine (using Live USB) renders rings as intended.

**Comment by Postrediori** [comment]
> However, my ring shader doesn't return any structs.

It seems that the version of `RING_SHADER_FRAGMENT` from `src/shaders.js` is not called from anywhere in the Saturn demo. Instead the shader is in `build/spacekit.js`.

> Warning: D3D shader compilation failed with default flags.

I've found out the similar error in the TensorFlow JS library (https://github.com/tensorflow/tfjs/issues/1337). It's not directly aplicable to this case, but the solution for that bug (https://github.com/tensorflow/tfjs-core/pull/1646) showed that there might be flaws hidden deep in a valid and working code because of the GPU drivers (like an inability to handle integer division correctly in TensorFlow case).

So I've checked the ring's frament shader for suspicious things. There is the following calculation of the pixel's colour:

```
  void main(void) {
	gl_FragColor = color() * vec4(lights() * shadow(), 1.0);
  }
```

The `color()` function contains `discard` option as the conditional path. 

```
  vec4 color() {
    ...
    if (...) {
      discard;
    }
    ...
  }
```

Commenting this out (or replacing with `return vec4(0.0)` as a second option) also fixes the problem (and renders 'wrong' rings of course).

My guess is that the driver on Windows cannot handle variable deallocation correctly. When an operand of the multiplication operation (`color()` function) calls `discard` it does not discard the multiplication operation as a whole. Light and shadow components are calculated anyway and when the second operand `vec4(...)` is calculated it tries to multiply the result by the left operand that has already been discarded and the driver crashes (hence the vague 'unbound variable' text in the error log).

Switching the operands of the final multiplication allows rings to be rendered:

```
	gl_FragColor = vec4(lights() * shadow(), 1.0) * color();
```

Also, saving light&shadow components to a temporary vector also works fine as right value is already known when `discard` in `color()` is executed:

```
        vec3 lightAndShadow = lights() * shadow();
	gl_FragColor = color() * vec4(lightAndShadow , 1.0);
```

This is just my first look on the problem and I'm not sure this is the final or 'proper' way to fix this.

P.S. The following version also works for some mysterious reason:

```
  void main(void) {
        vec3 foo = lights();
        vec3 bar = shadow();
	gl_FragColor = color() * vec4(lights() * shadow(), 1.0);
  }
```

**Comment by typpo** [comment]
@Postrediori Thanks so much for the detailed debugging help!  I've made one of your suggested changes:

	gl_FragColor = vec4(lights() * shadow(), 1.0) * color();

This means the example should load correctly (you may have to hard refresh): https://typpo.github.io/spacekit/examples/saturn/index.html.  How does it look?

**Comment by typpo** [comment]
Thank you again for the help!

**Comment by Postrediori** [comment]
FYI Maybe a bit late, I reported this issue to Chromium bugtracker: [https://bugs.chromium.org/p/chromium/issues/detail?id=1192924](https://bugs.chromium.org/p/chromium/issues/detail?id=1192924). It was labeled as Wont Fix though, because is is a bug somewhere in legacy DirectX dll.

**Comment by typpo** [comment]
This is interesting, thanks so much for following up.  I've run into strange issues with ANGLE before.
