### ISSUE TITLE
Just wanted to say hi as I've done something similar

### ISSUE THREAD

**Issue by mgreter** [typpo/spacekit#47]
First, cool stuff in this repo 👍 

Just wanted to give you a heads up that I did something similar in 2017/18, although in JavaScript, as
TypeScript wasn't really that mature or "hip" when I started my side project called "solar system explorer":

Latest demo of what I've implemented:
http://www.ocbnet.ch/solsys-preview-19 (chrome only)
FWIW the corresponding tweet with some screenshots:
https://twitter.com/mgreter/status/1402713051015565324

Unfortunately I haven't gotten around to publish much on GitHub, beside:
- https://github.com/mgreter/ephem.js (ported ephemeride theories with lots of tests)
- https://github.com/mgreter/astro.js (library to work with orbital elements -> similar to your Ephem class)
- https://github.com/mgreter/three.app (my application framework -> not up to date with latest demo)
- https://github.com/mgreter/sofa.js (complete port of IAU sofa suite with extensive test suite)

Anyway, found your repo just now as I'm slowly trying to publish my code on GitHub too.
Main reason that is hindering me is that I need to do proper asset copyright attribution yet.
Will probably poke around your repo a little to see if I can incorporate a thing or two into my project.
If you want to poke around my code, I also made an uncompressed version available at:
http://www.ocbnet.ch/solsys-preview-19/three-app-build/demo/solsys.dev.html

Hope you don't mind me opening an issue just to mention that.

**Comment by typpo** [comment]
Hey @mgreter,

This is really, really cool :) I must have missed the notification when you opened this issue back in June.  I'm having fun going through your code.  Thank you for sharing!
